In [3]:
print("1^5=",pow(1,5))

1^5= 1


In [4]:
print(abs(-100.9999))

100.9999


In [6]:
print(min(2,12,13,11))

2


In [7]:
print(2**5)

32


In [8]:
for i in range(0,6):
    print(2**i)

1
2
4
8
16
32


In [10]:
age=9
"Positive" if age>18 else "Negative"

'Negative'

In [12]:
name = input("Enter your name: ")
age = int(input("Enter your age: "))
print(f"Your Name: {name} and Age: {age}")

Enter your name:  aura
Enter your age:  52


Your Name: aura and Age: 52


In [15]:
age=19
if age>=18 and age<=20:
    print("You are college student.")
elif age>=21 and age<=30:
    print("You are a working professional.")
else: 
    print("You do not exist.")

You are college student.


In [38]:
name="surya Kumar yadav"
print(len(name))
print(name.find("-"))
print(name.capitalize())
print(name.upper())
print(name.lower())
print(name.count('u'))
print(name.replace(" ","*"))
print(name.isalpha())
digi="2345"
print(digi.isdigit())
print(name[0])
print(name[:2])
print(name[-4:])
print(name[::-1])

17
-1
Surya kumar yadav
SURYA KUMAR YADAV
surya kumar yadav
2
surya*Kumar*yadav
False
True
s
su
adav
vaday ramuK ayrus


In [61]:
addr="Ko"
print(addr*2)
lists=[1,2,3]
print(lists*2)

KoKo
[1, 2, 3, 1, 2, 3]


In [46]:
for i in range(11,0,-2):
    print(i)

11
9
7
5
3
1


In [55]:
i=4
while i>0 and i<11 :
    print(f"{i} Even" if i%2==0 else f"{i} Odd")
    i+=1


4 Even
5 Odd
6 Even
7 Odd
8 Even
9 Odd
10 Even


In [59]:
for i in range(1,6):
    for j in range(1,i+1):
        print("*",end="")
    print()

*
**
***
****
*****


In [64]:
for i in range(5,0,-1):
    print("*"*i)

*****
****
***
**
*


In [67]:
for i in range(0,6):
    print(" "*(5-i)+"*"*(2*i -1))

     
    *
   ***
  *****
 *******
*********


In [69]:
for i in range(5,0,-1):
    print((5-i)*" ",(2*i-1)*"*")

 *********
  *******
   *****
    ***
     *


In [71]:
for i in range(0,6):
    print(" "*(5-i+1)+"*"*(2*i -1))
for i in range(5,0,-1):
    print((5-i)*" ",(2*i-1)*"*")

      
     *
    ***
   *****
  *******
 *********
 *********
  *******
   *****
    ***
     *


In [81]:
var=1
for i in range(1,5):
    print(" "*(5-i+1),end="")
    for j in range(1,i+1):        
        print(var,end=" ")
        var+=1
    print()#this is Floyd's triangle

     1 
    2 3 
   4 5 6 
  7 8 9 10 


In [83]:
import math
math.sqrt(25)

5.0

In [90]:
print(5.0//3)

1.0


In [89]:
print(5/3)

1.6666666666666667


In [96]:

for i in range(5):
    num=1
    print(" "*(5-i),end=" ")
    for j in range(i+1):
        print(num,end=" ")
        num=num*(i-j)//(j+1)
    print()

      1 
     1 1 
    1 2 1 
   1 3 3 1 
  1 4 6 4 1 


In [101]:
for i in range(6):
    for j in range(6):
        if(i==0 or i==5 or j==0 or j==5):
            print("*",end="")
        else :
            print(" ",end="")
    print()

******
*    *
*    *
*    *
*    *
******


In [132]:
names=["Reva","Ani","Anki","Surya","Lion"]
for name in names:
    print(name)
names.append("Nika")
names.remove("Nika")
names.insert(2,"Luffy")
print(names)
print(names.count("Surya"))
print(names[::-1])
print(names.pop(3))
print(max(names))
digits=[1,3,2,5]
print(digits)
digits.sort()
print(digits)
digits.reverse()
print(digits)
print(f"Max. Element: {max(digits)} and Min. Element: {min(digits)} and Sum of Elements: {sum(digits)}")
print("Reva" in names)

Reva
Ani
Anki
Surya
Lion
['Reva', 'Ani', 'Luffy', 'Anki', 'Surya', 'Lion']
1
['Lion', 'Surya', 'Anki', 'Luffy', 'Ani', 'Reva']
Anki
Surya
[1, 3, 2, 5]
[1, 2, 3, 5]
[5, 3, 2, 1]
Max. Element: 5 and Min. Element: 1 and Sum of Elements: 11
True


In [139]:

print(st)
st.add(6)
print(st)
st.remove(4)
print(st)

{1, 2, 3, 4, 5}
{1, 2, 3, 4, 5, 6}
{1, 2, 3, 5, 6}


In [146]:
st={False,0,1,2,3,4,5,True}
print(st)
st.pop()
print(st)

{False, 1, 2, 3, 4, 5}
{1, 2, 3, 4, 5}


In [145]:
newst=set((1,2,3,4,5))
print(3 in newst)
print(type(newst))

True
<class 'set'>


In [147]:
print(newst.pop())

1


In [166]:
#tuples
tpl=(1,2,3,9,8,11,8)
print(tpl)
print(tpl*2)
print(tpl[0])
print(max(tpl))
print(tpl.index(8))
print(tpl.count(8))
print(5 in tpl)
lst=list(tpl)
lst.insert(0,7)
lst.remove(8)
tpl=tuple(lst)
print(tpl)
print("length:",len(tpl))
for x in tpl:
    print(x,end="/")
print()
for i in range(len(tpl)):
    print(tpl[i],end="-")

(1, 2, 3, 9, 8, 11, 8)
(1, 2, 3, 9, 8, 11, 8, 1, 2, 3, 9, 8, 11, 8)
1
11
4
2
False
(7, 1, 2, 3, 9, 11, 8)
length: 7
7/1/2/3/9/11/8/
7-1-2-3-9-11-8-

In [194]:
#python Dictionaries
dit={
    "Name":"Surya",
    "City":"Ara",
    "Age":90
}
print(dit["Name"])
print(len(dit))
keys=dit.keys()
vals=dit.values()
items=dit.items()
print(keys)
print(vals)
print(items)
dit["Gen"]="M"
print(items)
if "Gen" in dit:
    print("gen in present!")
else:
    print("Not present!")
dit.update({"Age":18})
print(items)
# dit.popitem()
# print(dit)
# dit.pop("Age")
# print(dit)
# del dit["Name"]
print(dit)

Surya
3
dict_keys(['Name', 'City', 'Age'])
dict_values(['Surya', 'Ara', 90])
dict_items([('Name', 'Surya'), ('City', 'Ara'), ('Age', 90)])
dict_items([('Name', 'Surya'), ('City', 'Ara'), ('Age', 90), ('Gen', 'M')])
gen in present!
dict_items([('Name', 'Surya'), ('City', 'Ara'), ('Age', 18), ('Gen', 'M')])
{'Name': 'Surya', 'City': 'Ara', 'Age': 18, 'Gen': 'M'}


In [200]:
obj1={
    "name":"obj111"
}
obj2={
    "name":"obj2"
}
obj3={"name":"obj3"}
nestdit={
    "child1":obj1,
    "child2":obj2,
    "child3":obj3
}
print(nestdit["child1"]["name"])
for x,y in nestdit.items():
    print(x)
    for z in y:
        print(z+y[z])
    print()

obj111
child1
nameobj111

child2
nameobj2

child3
nameobj3



In [204]:
def fun():
    return "Fun!"
def sum():
    pass
msg=fun()
print(msg)
print(sum())

Fun!
None


In [211]:
def sayhello(name,age=20,gen="M"):
    print(f"Hi, {name}! \nyou are {age} year olds and you are {"Male" if gen=="M" else "Female"}.")
sayhello(gen="F",age=90,name="surya")

Hi, surya! 
you are 90 year olds and you are Female.


In [215]:
def lsts():
    return [10,20,30]
nums=lsts()
print(nums[0])
nums[0]=100;
print(nums[0])
print(nums)

10
100
[100, 20, 30]


In [216]:
def fun(lst):
    lst[0]=90

req=[30,39,36]
print(req)
fun(req)
print(req)

[30, 39, 36]
[90, 39, 36]


In [225]:
tpl0=(22,32,99,89,78)
(x,*m)=tpl0
print(x,m[0])

22 32


In [227]:
def allSum(opr,*args):
    sum=0
    for arg in args:
        sum+=arg
    return f"{opr} {sum}"
print(allSum("Sum",10,23,13,15))

Sum 61


In [242]:
def showData(villa,*agrs,**person):
    print(f"{villa} Address: {agrs[0]},{agrs[1]},{agrs[2]}")
    for key,val in person.items():
        print(f"{key}:{val}")
userAddr=["Kafila","Kopa","UP","Mau"]
showData(*userAddr,name="surya",age=90,school="Aps",gen="M")

Kafila Address: Kopa,UP,Mau
name:surya
age:90
school:Aps
gen:M


In [248]:
def fun1():
    global x
    x=10
fun1()
print(x)

10


In [247]:
x=900
def fun2():
    global x
    x=77
fun2()
print(x)

77


In [251]:
def changefun(fun):
    def myinner():
        return fun().lower()
    return myinner

@changefun
def sayHi():
    return "Hillo world!"
print(sayHi())

hillo world!


In [3]:
#lambda function
x=lambda *a:sum(a)
print(x(8,9,6,11))

34


In [4]:
mydoubler=lambda a: a*2
print(mydoubler(8))

16


In [7]:
def multiplier(n):
    return lambda a:a*n
tripler= multiplier(3)
print(tripler(91))

273


In [8]:
words = ["hello", "python", "list", "comprehension", "is", "awesome"]
# Convert to uppercase only words longer than 4 letters
words=[x.upper() for x in words if len(x)>4]
print(words)

['HELLO', 'PYTHON', 'COMPREHENSION', 'AWESOME']


In [17]:
#syntax : [expression for x in iterable if condition]
#now nested list comprehensions
mlist=[[i*j for j in range(1,11)] for i in range(1,11)]
for x in mlist:
    print(x)

[1, 2, 3, 4, 5, 6, 7, 8, 9, 10]
[2, 4, 6, 8, 10, 12, 14, 16, 18, 20]
[3, 6, 9, 12, 15, 18, 21, 24, 27, 30]
[4, 8, 12, 16, 20, 24, 28, 32, 36, 40]
[5, 10, 15, 20, 25, 30, 35, 40, 45, 50]
[6, 12, 18, 24, 30, 36, 42, 48, 54, 60]
[7, 14, 21, 28, 35, 42, 49, 56, 63, 70]
[8, 16, 24, 32, 40, 48, 56, 64, 72, 80]
[9, 18, 27, 36, 45, 54, 63, 72, 81, 90]
[10, 20, 30, 40, 50, 60, 70, 80, 90, 100]


In [ ]:
newlst=[[] for i in range(5)]

In [3]:
line=input()
parts=line.split()


 surya kumar yadav


surya kumar yadav
['surya', 'kumar', 'yadav']


In [5]:
from statistics import mean
crr=[2,2,2,2,2]
print(mean(crr))

2


In [10]:
import numpy as np
from scipy import stats
arr=np.array([1,2,3,4,5,6,7,8,9,10])
print("Normal Mean: ",np.mean(arr))
print("Accurate Mean: ",stats.trim_mean(arr,0.1))

Normal Mean:  5.5
Accurate Mean:  5.5


In [40]:
import random
print(random.random())
print(random.randint(1,2))
print(random.choice([1,4,5]))
print(arr)
arr.sort()
print(arr)
random.shuffle(arr)
print(arr)

0.95261304591253
1
1
[ 5  9  4  3  6  2  8  7 10  1]
[ 1  2  3  4  5  6  7  8  9 10]
[10  4  5  8  9  2  7  6  1  3]


In [33]:
str4="Hello"
str4+"I"

'HelloI'

In [35]:
[0,3,2,2]

[0, 3, 2, 2]

In [55]:
f=open("hello.txt")
print(f.read(21))
f.close()

hello,this is surya!



In [171]:
with open("hello.txt") as f:
    print(f.readlines())


['hello,this is surya!\n', 'Hey, there this is me,\n', 'have you remembered me!']


In [53]:
with open("hello.txt") as f:
    for x in f:
        print(x+"CHANGE")

hello,this is surya!
CHANGE
Hey, there this is me,
CHANGE
have you remembered me!CHANGE


In [60]:
drr=["Hura","Assu","Buddy","Oann","Fly"]
print(drr)
drr.sort()
print(drr)
drr=sorted(drr,key=lambda x:len(x))
print(drr)

['Hura', 'Assu', 'Buddy', 'Oann', 'Fly']
['Assu', 'Buddy', 'Fly', 'Hura', 'Oann']
['Fly', 'Assu', 'Hura', 'Oann', 'Buddy']


In [63]:
students = [("Emil", 25), ("Tobias", 22), ("Linus", 28),("Emiil", 27), ("Tobiasaas", 42), ("Lixnus", 84)]
err=sorted(students,key=lambda x:x[1])
print(err)

[('Tobias', 22), ('Emil', 25), ('Emiil', 27), ('Linus', 28), ('Tobiasaas', 42), ('Lixnus', 84)]


In [71]:
students = [("Emil", 25), ("Tobias", 22), ("Linus", 28),("Emiil", 27), ("Tobiasaas", 72), ("Lixnus", 84)]
frr=list(filter(lambda x:x[1] > 50,students))
print(frr)

[('Tobiasaas', 72), ('Lixnus', 84)]


In [75]:
#recursion
def fact(n):
    if n==0 or n==1:
        return n
    else :
        return n*fact(n-1)
print(fact(2),fact(3),fact(4))
print("hi","hello","ha")

2 6 24
hi hello ha


In [80]:
def fib(n):
    if n==0 or n==1:
        return n
    else :
        return fib(n-1)+fib(n-2)
for i in range(9):
    print(fib(i),end=" ")

0 1 1 2 3 5 8 13 21 

In [84]:
with open("health.txt","w") as f:
    f.write("My health is very good. Even if do not do anything")

In [87]:
with open("health.txt") as f:
    print(f.read())

My health is very good. Even if do not do anything And i will live very long.


In [86]:
with open("health.txt","a") as f:
    f.write(" And i will live very long.")

In [91]:
import random
print(random.randint(0,5))
print(random.randint(0,5))
print(random.randint(0,5))
print(random.randint(0,5))
print(random.randint(0,5))
print(random.randint(0,5))
print(random.randint(0,5))
print(random.randint(0,5))

3
4
1
0
2
0
3
2


In [103]:
import datetime
print(datetime.datetime.now().year)
print(datetime.datetime.now().time())
print(datetime.date.today())
print(datetime.date(2002,12,3))
print(datetime.time(12,15,56,900000))
print(datetime.datetime(2006,10,2))

2026
08:45:09.212975
2026-04-17
2002-12-03
12:15:56.900000
2006-10-02 00:00:00


In [106]:
a=[10,20,30]
b=a.copy()
c=b[:]
b.append(40)
print(a)
print(b)
print(c)

[10, 20, 30]
[10, 20, 30, 40]
[10, 20, 30]


In [107]:
d=[1,2,3,4]
e=d.copy()
e[0]=44
print(e)
print(d)

[44, 2, 3, 4]
[1, 2, 3, 4]


In [111]:
lstr=[1,2,3,4,2,3,5]

gt=set(lstr)
print(lt)

[1, 2, 3, 4, 2, 3, 5]
(1, 2, 3, 4, 2, 3, 5)


In [118]:
def has_duplicates(L):
    ans=False
    for i in range(len(L)):
        if(L[i] in L[i+1:]):
            ans=True
            break
    return ans
has_duplicates([1,2,3,6,5,4,1])

True

In [126]:
str="a,b,c,d,e"
rst=str.split(",")
print(rst)

['a', 'b', 'c', 'd', 'e']


In [128]:
nums=[1,2,4,3,6]
numsr=["x","c","v","t"]
urr=",".join(numsr)
print(urr)
mini=sum(x for x in nums if x>3)
print(mini)

x,c,v,t
10


In [134]:
s1={1,2,3,4,5}
s2={3,4,5,6,7}
print(sorted(s1 & s2))
print(s1 | s2)

[3, 4, 5]
{1, 2, 3, 4, 5, 6, 7}


In [136]:
R={}
for i in range(11):
    R[i]=i*8
print(R)

{0: 0, 1: 8, 2: 16, 3: 24, 4: 32, 5: 40, 6: 48, 7: 56, 8: 64, 9: 72, 10: 80}


In [138]:
strr="aaabccdd"
dictn={}
for ch in strr:
    if(ch in dictn):
        dictn[ch]+=1
    else:
        dictn[ch]=1
print(dictn)

{'a': 3, 'b': 1, 'c': 2, 'd': 2}


In [145]:
def good(c):
    return float(c)
urr=[6,4,5]
lsy=list(map(good,urr))
print(lsy)

[6.0, 4.0, 5.0]


In [149]:
def mul(a,b):
    if(b==0):
        return 0
    return a+mul(a,b-1)
mul(0,1)
    

0

In [168]:
L=[11,23,22,42,25,7,62,99,87]
def mini(ind,L):
    if ind==0:
        return L[0]
    else:
        get=mini(ind-1,L)
        if(L[ind] < get ):
            return L[ind]
        else:
            return get
mini(len(L)-1,L)

7

In [174]:
print(list(set([9,8,7])))

[8, 9, 7]


In [177]:
ui=["abcd","ab","abcde"]
ans=""

for r in range(min(len(x) for x in ui)):
    prif=ui[0][r]
    for i in range(1,len(ui)):
        if (ui[i][r]==prif):
            ans+=prif
print(ans)

aabb


In [178]:
31//32

0

In [181]:
w,r,t="e-r-t".split("-")
print(w)

e


In [184]:
import calendar
cal = calendar.HTMLCalendar()
print(calendar.monthcalendar(2026, 4))

[[0, 0, 1, 2, 3, 4, 5], [6, 7, 8, 9, 10, 11, 12], [13, 14, 15, 16, 17, 18, 19], [20, 21, 22, 23, 24, 25, 26], [27, 28, 29, 30, 0, 0, 0]]


In [185]:
print(calendar.weekday(2026, 4, 18))

5
